spring.application.name=finanzas_framework

# ===========================
# Base de datos
# ===========================
spring.datasource.url=jdbc:mysql://localhost:3306/finanzas_framework?useSSL=false&serverTimezone=America/Bogota
spring.datasource.username=root
spring.datasource.password=12345

# ===========================
# JPA / Hibernate
# ===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true